# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Download\OneDrive - zju.edu.cn\code\EMGexe\EMG\ui\testMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.CC = QtWidgets.QWidget(MainWindow)
        self.CC.setObjectName("CC")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CC)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LL = QtWidgets.QVBoxLayout()
        self.LL.setObjectName("LL")
        self.tb = QtWidgets.QToolButton(self.CC)
        self.tb.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.tb.setObjectName("tb")
        self.LL.addWidget(self.tb)
        self.et_test = QtWidgets.QTextEdit(self.CC)
        self.et_test.setObjectName("et_test")
        self.LL.addWidget(self.et_test)
        self.verticalLayout_2.addLayout(self.LL)
        MainWindow.setCentralWidget(self.CC)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tb.setText(_translate("MainWindow", "..."))
